config/routes.rb
Dodat2::Application.routes.draw do
  root :to => "site#down"
  # root :to => "site#root"
    
  namespace :api, :defaults => { :format => :json } do
    resources :boards, except: [:new, :edit] do
      resources :lists, only: [:index, :show, :create, :update, :destroy]
    end
    
    resources :lists, only: [:show, :update, :destroy] do
      resources :cards, only: [:create, :index, :destroy]
    end
    
    resources :cards, only: [:show, :update, :destroy]
  end
  
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :destroy]
end

app/models/board.rb
class Board < ActiveRecord::Base
  validates :title, presence: true
  #validates :user_id, presence: true
  
  has_many :lists, dependent: :destroy
  has_many :cards, through: :lists
end

app/models/card.rb
class Card < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :list
  has_one :board, through: :list
end

app/models/list.rb
class List < ActiveRecord::Base
  validates :title, presence: true
  validates :board_id, presence: true
  belongs_to :board
  has_many :cards, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  
  before_validation :ensure_session_token  
  validates :username, :password_digest, :session_token, presence: true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :username, uniqueness: true
  
  has_many :boards, dependent: :destroy
    
  # session#create
  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end
  
  # user#find_by_credentials
  def is_password?(unencrypted_password)
   BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end
  
  def password=(unencrypted_password)
    if unencrypted_password.present?
      # creating this ivar allows us to perform validation check, but it will not be saved to the db, it will be hashed then saved
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end
  
  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  # blacklist password_digest
  def as_json(options = {})
    super(options.merge({ except: :password_digest, include: :cards }))
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/api/boards_controller.rb
class Api::BoardsController < ApplicationController
  before_action :require_login!
  def update
    @board = Board.find(params[:id])
    if @board.update_attributes(params[:board])
      render :json => @board
    else
      render :json => @board.errors, :status => :unprocessable_entity
    end
  end
  
  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    render :json => @board
  end
  
  def create
    @board = current_user.boards.new(board_params)
    
    if @board.save
      render :json => @board
    else
      render :json => @board.errors, :status => :unprocessable_entity 
    end
  end
  
  def index
    @boards = Board.where(["user_id = ?", current_user.id])
    render :index
  end
  
  def show
    @board = Board.find(params[:id])
    render :show
  end
  
  private
  
  def board_params
    params.require(:board).permit(:title)
  end
end

app/controllers/api/cards_controller.rb
class Api::CardsController < ApplicationController
  before_action :require_login!
  def create
    @card = Card.new(card_params)
    
    if @card.save
      render :json => @card
    else
      render :json => @card.errors, :status => :unprocessable_entity
    end
  end
  
  def show
    @card = Card.find(params[:id])
    render :json => @card
  end
  
  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    render :json => @card
  end
  
  private
  def card_params
    params.require(:card).permit(:title, :description, :list_id)
  end
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApplicationController
  # def index
  #   @lists  = List.where(:board_id => params[:board_id])
  #   render :json => @lists
  # end
  # 
  before_action :require_login!
  def show
    @list = List.find(params[:id])
    render :json => @list
  end
  
  def create
    @list = List.new(list_params)
    
    if @list.save
      render :json => @list
    else
      render :json => @list.errors, :status => :unprocessable_entity
    end
  end
  
  def update
  end
  
  def destroy
    @list = List.find(params[:id])
    @list.destroy
    render :json => @list
  end
  
  private
  
  def list_params
    params.require(:list).permit(:title, :board_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  protect_from_forgery with: :exception
  
  helper_method :logged_in?
  helper_method :current_user
  helper_method :username

  private
  def current_user
    session_token = session[:session_token]
    return nil if session_token.nil?
    @current_user ||= User.find_by_session_token(session_token)
  end
  
  def username
    current_user.username.capitalize
  end

  def login(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout
    session[:session_token] = nil
    current_user.reset_session_token! if logged_in?
  end

  def logged_in?
    !!current_user
  end

  def require_login!
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user
      login(user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid Username or Password"]
      render :new, status: 401
    end
  end
    
  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def root
    if !logged_in?
      redirect_to new_session_url
    else
      render "root"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      login(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new, status: 422
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/api/cards_helper.rb
module Api::CardsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    (<<-HTML).html_safe
<input name='authenticity_token'
       type='hidden'
       value='#{ form_authenticity_token }'>
HTML
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% flash[:errors] && flash[:errors].each do |error| %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" 
      class="close" 
      data-dismiss="alert" 
      aria-hidden="true">&times;</button>
    <strong>Error:</strong>
    <%= error %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Dodat</title>
	  <%= stylesheet_link_tag    "application", media: "all" %>
	  <%= javascript_include_tag "application"%>
	  <%= csrf_meta_tags %>
		<link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
	</head>
	<body> 
		<div class="header" id="header">
			
			<% if logged_in? %>
			<div class="header__boards-menu">
				<i class="upside-down fa fa-bar-chart-o"></i>
					<a href="#" class="header_board_text">Boards</a>
			</div>
			<% end %>
			
			<% if logged_in? %>
			<div class="header__brand">
				<h4 class="header__brand__text">
					<a href="#">DODAT</a>
				</h4>
			</div>
			<% end %>
			
			<% if !logged_in? %>
			<div class="header__brand">
				<h4 class="header__brand__text">
					<div class="header-intro-text">Welcome to DODAT!</div>
				</h4>
			</div>
			<% end %>
			
			<% if logged_in? %>
			<div class="header__section__right">
				<div class="header_section_right_account_menu">
					<% if username == "Steve" %>
						<span class="header_guest_name">
							Guest
						</span>
					<% else %>
					<span class="header_guest_name">
						<%= username %>
					</span>
					<% end %>
					<img class="account_avatar" src="http://www.gravatar.com/avatar/fbbd6b5524c2e0ee1bb0719a626d8330?s=64">
				</div>
				
			</div>
			<% end %>
				
		</div>
		
	<%= yield %>
	<% if logged_in? %>
	<%= button_to "Log out", session_url, { method: :delete, class: "btn btn-xs btn-warning" } %>
	<% end %>
	</body>
</html>

app/views/site/down.html.erb
<h1>Thanks for checking out my website. I am not currently seeking employment!</h1>

app/views/site/root.html.erb
<div id="content" class="container"></div>
<script>
$(function(){
  Dodat2.initialize();
});
</script>

app/views/users/new.html.erb
<!-- <div class="container" align="center">
	<div class="signinout">
  <%= render "layouts/errors" %>

	<h1>Dodat</h1>
  <h1>Sign Up</h1>

	  <form action="<%= users_url %>" method="POST">
	    <%= auth_token_input %>
	    <label>
	      <font color="#428bca">Username</font><br>
	      <input id="username" type="text" name="user[username]">
	    </label>
	    <br>
	    <label>
	      <font color="#428bca">Password</font><br>
	      <input id="password" type="password" name="user[password]">
	    </label>
	    <br>
	    <input type="submit" class="btn" value="Sign Up">
	    <a href="<%= new_session_url %>">Back to Login</a>
	  </form>
	</div>
</div> -->

<div class="container" align="center">
	<div class="signin-outer">
  	<%= render "layouts/errors" %>
			
		<h1 class="logo-text">Sign Up</h1>
		
	  <form action="<%= users_url %>" method="post">
	    <%= auth_token_input %>
	    <span class="form-labels">Username:</span>
				<br>
	      <input type="text" name="user[username]">
				<br>
	      <span class="form-labels">Password:</span>
				<br>
	      <input type="password" name="user[password]">
	    	<br><br>
	    <input type="submit" class="btn" value="Sign Up">
	    <a href="<%= new_session_url %>">Sign In</a>
	  </form>
	<br>
		<form action="<%= session_url%>" method="post">
			<%=auth_token_input %>
			<input type="hidden" name="user[username]" value="steve">
			<input type="hidden" name="user[password]" value="password">
			<input type="submit" class="btn btn-primary custom-button"value="Guest Login!">
		</form>
				
	</div>
</div>